CREATE TABLE tasks_json (
    id INT AUTO_INCREMENT PRIMARY KEY,
    task_data JSON NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO tasks_json (task_data) VALUES ('[]');
